[rofi]
file = "rofi"
parent = "/home/josh/.config"

[swaylock]
file = "swaylock"
parent = "~/.config"

[xplr]
file = "xplr"
parent = "~/.config"

[lectern]
file = "lectern"
parent = "/home/josh/.config"

[kanata]
file = "keybs"
parent = "~/.config"

[tmux]
file = ".tmux.conf"
parent = "/home/josh/"

[starship]
file = "starship"
parent = "~/.config"

[tex]
file = "texmf"
parent = "~/"

[waybar]
file = "waybar"
parent = "~/.config"

[fish]
file = "config.fish"
parent = "~/.config/fish"

[nvim]
file = "nvim"
parent = "~/.config"

[wezterm]
file = ".wezterm.lua"
parent = "~/"

[sway]
file = "sway"
parent = "~/.config"

[zathura]
file = "zathura"
parent = "~/.config"

[vim]
file = ".vimrc"
parent = "~/"

[dunst]
file = "dunst"
parent = "~/.config"
