[dunst]
file = "dunst"
parent = "~/.config"

[nvim]
file = "nvim"
parent = "~/.config"

[starship]
file = "starship"
parent = "/home/josh/.config"

[kanata]
file = "keybs"
parent = "~/.config"

[xplr]
file = "xplr"
parent = "~/.config"

[tofi]
file = "tofi"
parent = "~/.config"

[wezterm]
file = ".wezterm.lua"
parent = "~/"

[zathura]
file = "zathura"
parent = "~/.config"

[swaylock]
file = "swaylock"
parent = "~/.config"

[fish]
file = "/home/josh/.config/fish"
parent = "config.fish"

[vim]
file = ".vimrc"
parent = "~/"

[sway]
file = "sway"
parent = "~/.config"

[tex]
file = "texmf"
parent = "~/"

[waybar]
file = "waybar"
parent = "~/.config"
