[nvim]
file = "nvim"
parent = "~/.config"

[kanata]
file = "keybs"
parent = "~/.config"

[sway]
file = "sway"
parent = "~/.config"

[wezterm]
file = ".wezterm.lua"
parent = "~/"

[fish]
file = "config.fish"
parent = "~/.config/fish"

[waybar]
file = "waybar"
parent = "~/.config"

[vim]
file = ".vimrc"
parent = "~/"

[dunst]
file = "dunst"
parent = "~/.config"

[zathura]
file = "zathura"
parent = "~/.config"

[tex]
file = "texmf"
parent = "~/"

[starship]
file = "starship"
parent = "~/.config"

[tofi]
file = "tofi"
parent = "~/.config"

[tmux]
file = ".tmux.conf"
parent = "/home/josh/"

[xplr]
file = "xplr"
parent = "~/.config"

[swaylock]
file = "swaylock"
parent = "~/.config"
