[fish]
file = "config.fish"
parent = "/home/josh/.config/fish"

[wallust]
file = "wallust"
parent = "/home/josh/.config"

[kitty]
file = "kitty.conf"
parent = "/home/josh/.config"

[kanata]
file = "keybs"
parent = "/home/josh/.config"

[zathura]
file = "zathura"
parent = "/home/josh/.config"

[tmux]
file = ".tmux.conf"
parent = "/home/josh"

[tex]
file = "texmf"
parent = "/home/josh"

[waybar]
file = "waybar"
parent = "/home/josh/.config"

[sway]
file = "sway"
parent = "/home/josh/.config"

[nvim]
file = "nvim"
parent = "/home/josh/.config"

[vim]
file = ".vimrc"
parent = "/home/josh"

[wezterm]
file = ".wezterm.lua"
parent = "/home/josh"

[xplr]
file = "xplr"
parent = "/home/josh/.config"

[lectern]
file = "lectern"
parent = "/home/josh/.config"

[rofi]
file = "rofi"
parent = "/home/josh/.config"
