[starship]
file = "starship.toml"
parent = "/home/josh/.config"

[dunst]
file = "dunst"
parent = "~/.config"

[swaylock]
file = "swaylock"
parent = "~/.config"

[vim]
file = ".vimrc"
parent = "~/"

[tofi]
file = "tofi"
parent = "~/.config"

[tex]
file = "texmf"
parent = "~/"

[fish]
file = "fish"
parent = "~/.config"

[nvim]
file = "nvim"
parent = "~/.config"

[kanata]
file = "keybs"
parent = "~/.config"

[zathura]
file = "zathura"
parent = "~/.config"

[xplr]
file = "xplr"
parent = "~/.config"

[sway]
file = "sway"
parent = "~/.config"

[waybar]
file = "waybar"
parent = "~/.config"

[wezterm]
file = ".wezterm.lua"
parent = "~/"
