palette = "catppuccin"

[palettes.catppuccin]
id_color = "#f0c6c6" # flamingo

[character]
disabled = false
success_symbol = '[󰑂─󰁔](fg:id_color)'
error_symbol = '[󰑂┤](fg:id_color)[󰁔](fg:red)'
vimcmd_symbol = '[󰑂┤](fg:id_color)[](fg:green)'
vimcmd_replace_one_symbol = '[󰑂┤](fg:id_color)[](fg:mauve)'
vimcmd_replace_symbol = '[󰑂┤](fg:id_color)[](fg:mauve)'
vimcmd_visual_symbol = '[󰑂┤](fg:id_color)[](fg:yellow)'
