["8.333"]
name = "8.333"
title = "Statistical Mechanics I"
prof = "Julien Tailleur"
semester = "f25"

[PHYS253A]
name = "PHYS253A"
title = "Quantum Field Theory I"
prof = "Matthew Schwartz"
semester = "f25"

["8.324"]
name = "8.324"
title = "Relativistic Quantum Field Theory II"
prof = "Iain Stewart"
semester = "f25"
