["8.333"]
name = "8.333"
title = "Statistical Mechanics I"
prof = "Julien Tailleur"
semester = "f25"

[PHYS253A]
name = "PHYS253A"
title = "Quantum Field Theory I"
prof = "Matthew Schwartz"
semester = "f25"
